dashscope:
  api-key: 你的通义千问API密钥 

alipay:
  appId: 你的APPID
  privateKey: 你的私钥
  publicKey: 支付宝公钥
  notifyUrl: http://你的域名/api/alipay/notify
  returnUrl: http://你的域名/api/alipay/return
  gateway: https://openapi.alipaydev.com/gateway.do 