server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: 123456 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/xm_shopping_manager?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      # 在您的 application.yml 中添加以下配置


# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost

# 通义千问API配置
dashscope:
  api:
    key: sk-0234ae307b064bc78a4f2ad53adc50cd

alipay:
  appId: 2021000148613275
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHHsE+RloURYeQiKju0uUOCWjRGeVN//Jub2f2PYXnPeWo5aMa2Fvo/oJm/uPsFzjezFedx28GxTGNC07sfNKJrYv0mWrn65z41iUmcAQwhsdq9dRIQ/Htgzyn06lC12jVlUhU2Tid8jWB783uTI0royuMMQ9DYIGYpdGGdzinYZpswL4f4itDHvOQ/yE+vKBX3f4sWQRAcrHEj1PQoxjhfIY959tkBHcQAl869BqMPbtOWj4Kiy6QYnN6JXsL92AKes1leZvF/49wTSZtoo+H6EYCluUtnmr9A4A2MwVctAfF4D4SjGOCm22fJ5UKK1VFR08VlQnNxB4kzZULenGHAgMBAAECggEAVuE5aeWiWiP4QX0PUJ0eKiC65jmJTp41djAPyWYQrdPZB/eiUg1DFQcveKcQZavAOZ4pQIOLEwYpV6QufIr+Bep+HWxvM+Ae7ofpT7siaNX13tqCFEHpJjvT1FpLCQoaCM8I71SUGn5bEGXEkYw/MGISlym0wi4yfZskL6qHQqhS3Lm0w0ao4gP0H+u63oQezhMG9CsUqryu49A79tgNDweyT0HIo7roxZxiHHnR7ERqpHpgGi+7y+V70tAS27tChGjoAXBv43TVM4YtiJ/niHcsnFW6ZlTvIC02LB2uFherN84GeySXLOf+IbNLg6mnhZCzULCTs6cVqxrpyJhfYQKBgQD1CUB34iQEoN5Y/o4E0t9nHKvZdag64afMTGITvGmii/87LFHVdwLSkWVHMXqIcykD5VgaEyJRHfJfIWXtK1PFUhI3asdjv9q+gxvZqommbka4ge7pGC2wIFpwMB8TDfn+kpoOdSf6lihi5xmm8jSNr42ESZcivWUJo5fbd/f8twKBgQDQB4/EWQ2s8Z5mKiCVif+t5mOmr5mMDjKv9tQKHKheO5d6AfZ/WHNmIEK6i87CnIUpfooLgLw5FJEwUij5ZCSZsZnLbqfJPsxnNfuelPFSF9NEE960mLo6D0jPVpJ7H5fn4iS1qSoNyl/NZ77isDg2byWeV/eGWxLtISJX7zgBsQKBgQDn+eZKmJC4wQM/BV62Oly9ZWtb6ANoGxGcXAPN42WuORNclcyzZoQJjRRwner/GucNhSYvKUYnvU4juZ6hNY+NEvGj/TbevFb+XWkUXFsMcQIK0xe3HOjEAR0dcLE6fNTbqTan0UoT9ewuFdM3Nb2DFVvIjVLD1MG+ql2trJndaQKBgBJeiJBi+LUrxLvqvmPWArC9ZlFCskFOw6UMG58k9q0TgAWzBKwsCEydTqcgT0qZ/ZwzY0cuv/AeY8+rgZi8AgtcRmNTSxeXJv96IdTX/BMurWYWhxTVY6Ra0ygT0e1zVbuRGYK9BEyhcSI3JgDoZJ5R5DV+OQoxIpOz2E+BfSWRAoGAGQ8QMoxNmGEknyPrDzkjX/jZvSAaoMpis9E7sasp179vZc3VsFASm8wmbY+eWXbufBll51284O1HQFiRbeGKX5kRe+sTB7N8VKaeDmVcmyn1lvya6SlMle397b/YAbIHdeScVWeQPfo/HLyYkurt2XJ0ryXJK0lUWH97qZHrUFg=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt1PWGbOOqUxEzlCmxAlYq5210mKqCLenXBFxdyJ42V1ikpfk/+eqJUlPY5VvL5YT0GMsXb+ntWTtTuyivs5xtZ/3YfWo/LSAyRYFn8kWlnY8BDcWLPfRtNpDavZycStAHo1srBLT25ffbZfliDUrWCvSY34QrDhsyFfOwqsLGoSwuBu358VU+qLYZJ/yh1bDLRQ16EDFfBKJPsdCcqOxBpAORTJ1I6xAc1+youJxG13v4DfMhaPGnnEURGu++8egURAtvQtOO36lDwrThZtNgHvzKyH8zjWbce+1H9wW6dVrnRCAnqSiaAmAn0jGUdD9DOA3XUAQcsVzhZgRISVTOQIDAQAB
  notifyUrl: http://bbt8cz.natappfree.cc/api/alipay/notify
  returnUrl: http://bbt8cz.natappfree.cc/api/alipay/return
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
